@echo off
echo Starting Vite...
start /B npm run dev
timeout /t 5 /nobreak
echo Testing connection...
curl -I http://127.0.0.1:5173
echo.
echo Waiting 30 seconds to see if Vite stays alive...
timeout /t 30 /nobreak
echo Testing connection again...
curl -I http://127.0.0.1:5173
echo.
echo Killing Vite...
taskkill /F /IM node.exe
pause
